# Generated by Django 3.1.3 on 2020-12-15 06:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20201125_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='last_edit',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
