# Generated by Django 3.1.4 on 2020-12-15 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20201215_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-last_edit']},
        ),
    ]
